<?php

const RUNKIT_ACC_RETURN_REFERENCE = 4096;
const RUNKIT7_ACC_RETURN_REFERENCE = 4096;
const RUNKIT_ACC_PUBLIC = 1;
const RUNKIT7_ACC_PUBLIC = 1;
const RUNKIT_ACC_PROTECTED = 2;
const RUNKIT7_ACC_PROTECTED = 2;
const RUNKIT_ACC_PRIVATE = 4;
const RUNKIT7_ACC_PRIVATE = 4;
const RUNKIT_ACC_STATIC = 16;
const RUNKIT7_ACC_STATIC = 16;
const RUNKIT_OVERRIDE_OBJECTS = 32768;
const RUNKIT7_OVERRIDE_OBJECTS = 32768;
const RUNKIT_FEATURE_MANIPULATION = 1;
const RUNKIT7_FEATURE_MANIPULATION = 1;
const RUNKIT_FEATURE_SUPERGLOBALS = 1;
const RUNKIT7_FEATURE_SUPERGLOBALS = 1;
